# Dockerfile
FROM node:20-alpine

WORKDIR /app

# Alleen package-files eerst voor cache
COPY package*.json ./

# Prod dependencies
RUN npm ci --omit=dev || npm install --omit=dev

# App-code kopiëren
COPY . .

ENV NODE_ENV=production
EXPOSE 3000

# Start
CMD ["node", "src/server.js"]
